### ISSUE TITLE
pre compiled version : a more ES5 compliant build

### ISSUE THREAD

**Issue by jviala-ekino** [moducks/moducks#4]
Hi,

It seems that UglifyJS cannot parse some remaining es6 features in your pre-compiled version of moducks.

Here is the output of `npm run build` from a create-react-app :

```
static/js/main.5b8c93f6.js from UglifyJs
Invalid assignment [./~/moducks/es/utils.js:11,0][static/js/main.5b8c93f6.js:7849,47]
```

If you wanna try, here is my project https://gitlab.com/MrWildcard/a-nice-app/-/jobs/31180103 on `develop` branch.

Interesting lib btw!

**Comment by mpyw** [comment]
@jviala-ekino Thank you for reporting!

I found that pre-compiled files lying in `./es/` are still contain es6 features, so we should completely translate into es5 syntax. We'll improve it as soon as possible.

However, we suggest you using [babel/minify](https://github.com/babel/minify) instead of [mishoo/UglifyJS](https://github.com/mishoo/UglifyJS).

**Comment by mpyw** [comment]
Fixed in `0.2.0-rc4` release

**Comment by jviala-ekino** [comment]
💯

> However, we suggest you using babel/minify instead of mishoo/UglifyJS

Yes, I also found these alternatives. I'd have use them if I wasn't using create-react-app, but I'd have to eject my create-react-app to use them 😅

Thanks!

**Comment by jviala-ekino** [comment]
It seems that UglifyJS doesn't like it, yet :

```
static/js/main.92e05a43.js from UglifyJs
Invalid assignment [./~/moducks/es/utils.js:3,0][static/js/main.92e05a43.js:7792,27]
```

https://gitlab.com/MrWildcard/a-nice-app/-/jobs/31209531

In the meantime, I'll give a try to babel's minifier.

**Comment by mpyw** [comment]
Related: [UglifyJs Syntax Error fails `npm run build` but not `npm start` · Issue #984 · facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app/issues/984)

**Comment by mpyw** [comment]
@jviala-ekino 

I tried to fix by the following steps:

1. `npm run eject`
2. Write `{ resolve: { mainFields: ['main'] }}` in generated `webpack.config.prod.js`

However, `UglifyJSPlugin` still reads sources in `./es`, not in `./lib`. WTF...

**Comment by mpyw** [comment]
PR: [WIP: Use es5 instead of es6 modules (!22) · Merge Requests · Julien Viala / a-nice-app · GitLab](https://gitlab.com/MrWildcard/a-nice-app/merge_requests/22)

**Comment by jviala-ekino** [comment]
Thank you for your MR !

Indeed, I spent quite some times on this one and couldn't figure out why Webpack fallback on `module` as `mainField`. Webpack's doc says that this happens when a Node environment is detected.

I don't think it's create-react-app faults.. Anyway, what is exactly behind keeping the `es/` folder, instead of a unique one ?

**Comment by mpyw** [comment]
> Webpack's doc says that this happens when a Node environment is detected.

Umm, would you paste here the doc URL?

> Anyway, what is exactly the reason behind keeping the es/ folder, instead of a single one ?

- ES5 will die in the future and ES20xx is going to be the standard. We should support both formats until the time comes. Major projects follow this rule. (e.g. [redux-saga/package.json](https://github.com/redux-saga/redux-saga/blob/master/package.json) )
- ES5 transpilation causes some overheads.

**Comment by mpyw** [comment]
I found the statement:

> Meanwhile, a Node.js application bundled by webpack will resolve by default to the file in the module field.

But it says `"by default"`. It should be configurable. why...

**Comment by mpyw** [comment]
I found a very important opinion here:

[ES Modules in node_modules. How to transpile? · Issue #2902 · webpack/webpack](https://github.com/webpack/webpack/issues/2902)

> jsnext:main or module code should always already be transpiled. The only difference is that they use ES6 module syntax instead of commonjs function calls.

I'm going to fix based on this opinion. Please wait a while.

**Comment by mpyw** [comment]
Fixed in `0.2.0-rc.6` release

**Comment by jviala-ekino** [comment]
@mpyw 💯

thanks !

**Comment by mpyw** [comment]
I made a little mistake; The new version should be `0.2.0` but it's actually `0.2.1` now...
The missing number was born 🤦‍♂️
